services:
  portfolio-blue:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: daniel-koryat-portfolio-blue
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/api/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - portfolio-network

  portfolio-green:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: daniel-koryat-portfolio-green
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/api/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - portfolio-network

  nginx:
    image: nginx:alpine
    container_name: portfolio-nginx
    ports:
      - "8080:80" 
    volumes:
      # Mount the main config (read-only)
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount the file that controls the active upstream (read-only)
      - ./active_upstream.conf:/etc/nginx/conf.d/active_upstream.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nginx -t && curl -f http://localhost/nginx-health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - portfolio-network
      
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    depends_on:
      nginx:
        condition: service_healthy
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge