services:
  portfolio:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: daniel-koryat-portfolio
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 60s
    networks:
      - portfolio-network

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: portfolio-nginx:custom
    container_name: portfolio-nginx
    ports:
      - "8080:80" 
    volumes:
      # Mount the main config (read-only)
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
      portfolio:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nginx -t && curl -f http://localhost/nginx-health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge