services:
  portfolio:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: daniel-koryat-portfolio
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 60s
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge