services:
  portfolio-blue:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: daniel-koryat-portfolio-blue
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - portfolio-network

  portfolio-green:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: daniel-koryat-portfolio-green
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - portfolio-network

  nginx:
    image: nginx:alpine
    container_name: portfolio-nginx
    ports:
      - "8080:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - portfolio-network
      
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    depends_on:
      - nginx
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge