services:
  # Blue environment for portfolio
  portfolio-blue:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: daniel-koryat-portfolio-blue
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - portfolio-network

  # Green environment for portfolio (initially inactive)
  portfolio-green:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: daniel-koryat-portfolio-green
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - portfolio-network
    profiles:
      - inactive

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: portfolio-nginx
    ports:
      # Expose on 8080 for local testing
      - "8080:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - portfolio-blue
    restart: unless-stopped
    networks:
      - portfolio-network
      
  # Cloudflare Tunnel (Now managed by Docker Compose)
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    depends_on:
      - nginx
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
