name: 🚀 Quick Deploy (No Security Scan)

permissions:
  contents: read
  actions: read

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: false
        default: 'production'
        type: choice
        options:
          - production
          - staging

env:
  CONTAINER_PREFIX: daniel-koryat-portfolio
  CONTAINER_PORT: '3000'

jobs:
  deploy:
    name: 🚀 Deploy Application
    runs-on: self-hosted
    environment: ${{ inputs.environment }}
    
    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v4
    
    - name: 🐳 Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true
    
    - name: 🔧 Setup Docker Compose Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.docker/cli-plugins/docker-compose
          /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ hashFiles('**/docker-compose.yml') }}
        restore-keys: |
          ${{ runner.os }}-docker-
    
    - name: 🧹 Clean Up Existing Containers
      run: |
        echo "🧹 Force removing any existing containers to prevent name conflicts..."
        docker rm -f "${{ env.CONTAINER_PREFIX }}-blue" 2>/dev/null || true
        docker rm -f "${{ env.CONTAINER_PREFIX }}-green" 2>/dev/null || true
        docker container prune -f
        echo "✅ Container cleanup completed"
    
    - name: 🔧 Create Initial Upstream Config
      run: |
        if [ ! -f active_upstream.conf ]; then
          echo "Creating initial active_upstream.conf, pointing to blue..."
          echo "set \$active_upstream ${{ env.CONTAINER_PREFIX }}-blue:${{ env.CONTAINER_PORT }};" > active_upstream.conf
        fi
    
    - name: 🌐 Ensure Core Infrastructure
      run: |
        echo "🚀 Ensuring nginx and cloudflared are running..."
        docker compose up -d --remove-orphans nginx
        
        # Enhanced health check with timeout
        timeout_seconds=60
        elapsed=0
        
        while [ $elapsed -lt $timeout_seconds ]; do
          HEALTH_STATUS=$(docker inspect --format '{{.State.Health.Status}}' portfolio-nginx 2>/dev/null || echo "starting")
          if [ "${HEALTH_STATUS}" == "healthy" ]; then
            echo "✅ Nginx is healthy!"
            docker compose up -d --remove-orphans cloudflared
            break
          fi
          echo "⏳ Waiting for Nginx to be healthy... (Status: ${HEALTH_STATUS})"
          sleep 6
          elapsed=$((elapsed + 6))
        done
        
        if [ $elapsed -ge $timeout_seconds ]; then
          echo "❌ Nginx failed to start within timeout. Check logs."
          docker compose logs nginx
          exit 1
        fi
    
    - name: 🎯 Determine Deployment Slots
      id: determine_slots
      run: |
        if grep -q "blue" active_upstream.conf; then
          LIVE_SLOT="blue"
          DEPLOY_SLOT="green"
        else
          LIVE_SLOT="green"
          DEPLOY_SLOT="blue"
        fi
        
        echo "🔵 Live environment: ${LIVE_SLOT}"
        echo "🟢 Deploying to: ${DEPLOY_SLOT}"
        
        echo "LIVE_SLOT=${LIVE_SLOT}" >> $GITHUB_ENV
        echo "DEPLOY_SLOT=${DEPLOY_SLOT}" >> $GITHUB_ENV
        echo "live_slot=${LIVE_SLOT}" >> $GITHUB_OUTPUT
        echo "deploy_slot=${DEPLOY_SLOT}" >> $GITHUB_OUTPUT
    
    - name: 🔨 Build and Deploy New Version
      run: |
        echo "🚀 Building and deploying ${{ env.CONTAINER_PREFIX }}-${{ env.DEPLOY_SLOT }}..."
        
        # Build with cache
        DOCKER_BUILDKIT=1 docker compose build --build-arg BUILDKIT_INLINE_CACHE=1 "${{ env.CONTAINER_PREFIX }}-${{ env.DEPLOY_SLOT }}"
        
        # Deploy the new version with orphan removal
        docker compose up -d --force-recreate --remove-orphans "${{ env.CONTAINER_PREFIX }}-${{ env.DEPLOY_SLOT }}"
    
    - name: 🔍 Wait for New Environment Health
      run: |
        CONTAINER_NAME="${{ env.CONTAINER_PREFIX }}-${{ env.DEPLOY_SLOT }}"
        timeout_seconds=300
        elapsed=0
        
        echo "🔍 Waiting for ${CONTAINER_NAME} to become healthy..."
        
        while [ $elapsed -lt $timeout_seconds ]; do
          HEALTH_STATUS=$(docker inspect --format '{{.State.Health.Status}}' ${CONTAINER_NAME} 2>/dev/null || echo "starting")
          if [ "${HEALTH_STATUS}" == "healthy" ]; then
            echo "✅ ${CONTAINER_NAME} is healthy!"
            break
          fi
          echo "⏳ Waiting... (Status: ${HEALTH_STATUS}) - ${elapsed}s elapsed"
          sleep 10
          elapsed=$((elapsed + 10))
        done
        
        if [ $elapsed -ge $timeout_seconds ]; then
          echo "❌ ${CONTAINER_NAME} failed to become healthy. Aborting."
          docker compose logs "${{ env.CONTAINER_PREFIX }}-${{ env.DEPLOY_SLOT }}"
          exit 1
        fi
    
    - name: 🔄 Switch Traffic (Zero Downtime)
      run: |
        echo "🔄 Switching traffic from ${{ env.LIVE_SLOT }} to ${{ env.DEPLOY_SLOT }}..."
        
        # Backup current config
        cp active_upstream.conf active_upstream.conf.backup
        
        # Create a temporary config with both upstreams for smooth transition
        echo "set \$active_upstream ${{ env.CONTAINER_PREFIX }}-${{ env.DEPLOY_SLOT }}:${{ env.CONTAINER_PORT }};" > active_upstream.conf.tmp
        echo "set \$backup_upstream ${{ env.CONTAINER_PREFIX }}-${{ env.LIVE_SLOT }}:${{ env.CONTAINER_PORT }};" >> active_upstream.conf.tmp
        
        # Atomically switch the upstream
        mv active_upstream.conf.tmp active_upstream.conf
        
        # Perform graceful nginx reload with connection draining
        echo "🔄 Performing graceful nginx reload with connection draining..."
        
        # Send SIGUSR1 to nginx for graceful reload (drains existing connections)
        docker compose exec nginx nginx -s reload
        
        # Wait a moment for connections to drain
        echo "⏳ Waiting for connections to drain..."
        sleep 5
        
        # Verify the new environment is still healthy after traffic switch
        NEW_CONTAINER="${{ env.CONTAINER_PREFIX }}-${{ env.DEPLOY_SLOT }}"
        HEALTH_STATUS=$(docker inspect --format '{{.State.Health.Status}}' ${NEW_CONTAINER} 2>/dev/null || echo "none")
        
        if [ "${HEALTH_STATUS}" == "healthy" ]; then
          echo "✅ Traffic switched successfully! New environment is healthy."
        else
          echo "❌ New environment is not healthy after traffic switch. Rolling back..."
          
          # Rollback to previous configuration
          mv active_upstream.conf.backup active_upstream.conf
          docker compose exec nginx nginx -s reload
          
          echo "❌ Deployment failed - rolled back to previous environment"
          exit 1
        fi
    
    - name: 🧹 Clean Up Old Environment
      run: |
        echo "🛑 Stopping the old ${{ env.LIVE_SLOT }} container..."
        docker compose stop "${{ env.CONTAINER_PREFIX }}-${{ env.LIVE_SLOT }}" || true
        
        # Clean up old images (keep last 2 versions)
        docker image prune -f --filter "until=72h" || true
    
    - name: 📊 Deployment Summary
      run: |
        echo "🎉 Quick deployment complete!"
        echo "📈 Deployment Summary:"
        echo "  • Environment: ${{ inputs.environment }}"
        echo "  • Deployed Slot: ${{ env.DEPLOY_SLOT }}"
        echo "  • Previous Slot: ${{ env.LIVE_SLOT }}"
        echo "  • Container: ${{ env.CONTAINER_PREFIX }}-${{ env.DEPLOY_SLOT }}"
        echo "  • Time: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
        
        docker compose ps 